apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-k8s
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
      - name: spring-boot-k8s-app
        image: my-spring-boot-k8s-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-k8s-service
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

